import LandingPage from "./LandingPage";
import BackgroundOnePic from "../Assests/background-one.jpg";
import image3 from "../Assests/image3.png";
import creationnft from "../Assests/Creation NFT.png";
import rectangle18776 from "../Assests/Rectangle 18776.png";
import Group96898 from "../Assests/Group96898.png";
import Group96900 from "../Assests/Group96900.png";
import Group96896 from "../Assests/Group96896.png";
import Group96899 from "../Assests/Group96899.png";
import Group96897 from "../Assests/Group96897.png";
import Group96901 from "../Assests/Group96901.png";
import Group56 from "../Assests/Group56.png";
import Background from "../Assests/Background.png";
import D2one from "../Assests/D2one.png";
import BlueSmokeRing1 from "../Assests/BlueSmokeRing1.png";
import SkyContainers from "./SkyContainers";
import Frame53 from "../Assests/Frame53.png";
import Hero from "../Assests/hero.png";
import Phases from "./Phases";

const FirstPage = () => {
  return (
    <>
      <div
        className="bg-cover bg-center min-h-[100vh]"
        style={{ backgroundImage: `url(${BackgroundOnePic})` }}
      >
        <div>
          <LandingPage />
        </div>

        <div class="container pt-20 px-[15px]   mx-auto flex-col  min-h-screen">
          <div class="max-w-[90%] gap-[4vh] flex  flex-col">
            <h6
              className="lg:text-7xl md:text-5xl text-4xl leading-10 max-w-[650px] text-white font-normal"
              style={{ lineHeight: 1, fontFamily: "Zen Dots" }}
            >
              Generate with Ai, Scan, Mint, Sell & Trade.
            </h6>
            <h1 class="max-w-[380px]  text-white">
              Explore 3dotlink, where Web3 meets cultural legacy, and AI
              breathes life into NFTs.
            </h1>
            <div class="flex justify-between max-w-[60%]">
              <button class="bg-[#EF203B]  min-w-36    text-white rounded-md min-h-[8vh] text-sm font-semibold text-center">
                Buy NFT'S
              </button>
            </div>
          </div>
        </div>
      </div>
      <hr
        className="min-h-[3vh] bg-[#A70B09]"
        style={{ margin: "0", padding: "0", border: "none" }}
      />

      {/* OVER VISION SECTION START  */}
      <div
        className="text-center bg-cover bg-center min-h-[100vh] py-20 px-[15px]"
        style={{ backgroundImage: `url(${image3})` }}
      >
        <div className="container mx-auto ">
          <h6
            className="mb-10 text-5xl md:text-7xl font-semibold text-white "
            style={{ lineHeight: 0.8, fontFamily: "Zen Dots" }}
          >
            Our Vision
          </h6>
          <p className="text-white mb-10">
            The vision of 3dotlink is to be a transformative force at the
            intersection of culture, art, and technology within the Web3
            landscape. We envision a digital realm where the rich tapestry of
            cultural traditions, especially the intricate artistry of masks from
            diverse ethnic groups, is seamlessly woven into the fabric of the
            digital age. Our vision extends far beyond mere NFTs; it's about the
            preservation and celebration of cultural heritage in a dynamic,
            ever-evolving digital space. We strive to empower artists and
            creators, offering them a unique canvas to bring their cultural art to
            life while harnessing the capabilities of AI technology. We see
            3dotlink as a bridge between the past and the future, where ancient
            rituals and modern innovation converge, enriching our collective human
            experience and fostering a global community united by a shared
            appreciation for the art, history, and culture that defines us. In
            essence, our vision is to unlock the immense potential of cultural art
            within Web3, inviting the world to explore, create, and treasure the
            beauty of diverse traditions through the digital realm.
          </p>
          <button class="bg-[#EF203B]  min-w-[100px]    text-white rounded-md min-h-[6vh] text-sm font-semibold text-center">
            Read More
          </button>
        </div>
      </div>
      <hr
        className="min-h-[5vh] bg-black"
        style={{ margin: "0", padding: "0", border: "none" }}
      />
      <img src={creationnft} alt="" className="h-[40vh] w-[100vw]" />

      <SkyContainers />

      <div style={{ backgroundImage: `url(${Background})` }} className="py-20">
        <div className="container mx-auto">
          <div className="text-center">
            <h6
              className=" text-5xl mb-5 text-white font-normal"
              style={{ lineHeight: 1, fontFamily: "Zen Dots" }}
            >
              Popular NFT’s generated by Artists
            </h6>
            <p className="text-[white] mb-16">
              3dotlink's AI integration is a game-changer in the NFT art world. It
              offers a powerful canvas for artists to redefine art creation and
              innovation while preserving cultural art in an entirely new format.
              With this platform, the convergence of human ingenuity and AI
              technology is set to redefine the boundaries of artistic expression
              and creative possibilities, ushering in a digital art renaissance.
            </p>
          </div>

          <div className="flex gap-4">

            <div className="w-[20%]">
              <div className="">

                <img src={rectangle18776} className="w-full" />
              </div>
              <div className="mt-5">
                <img
                  src={Group96896}
                  className="w-full"

                />
              </div>
            </div>

            <div className="w-[80%]">
              {/* ROW */}
              <div className="flex gap-4">
                <div className="w-[60.8%]">
                  <img src={Group96898} className="w-full" />

                </div>
                <div className="w-[29%]">
                  <div className="">
                    <img src={Group96897} className="w-full" />
                  </div>
                  <div className="mt-5">
                    <img src={Group96900} className="w-full" />
                  </div>
                </div>
              </div>
              {/* ROW */}

              <div className="flex  g-4 mt-4">
                <div className="w-[30%] h-[135px]">
                  <img
                    src={Group96901} className="w-full h-full object-cover" />
                </div>

                <div className="w-[60%] ms-4  h-[135px] overflow-hidden">
                  <img src={Group96899} className="w-full h-full object-cover" />

                </div>

              </div>
            </div>


          </div>


          {/* <div className="flex justify-center items-center text-white mt-14">
            <div className="grid grid-cols-4 grid-rows-3 gap-5 h-screen w-10/12 justify-center items-center">
              <div className="col-span-1" >
                <img src={rectangle18776} />

              </div>
              <div className="" style={{ gridArea: "2 / 1 / 4 / 2" }}>

                <img
                  src={Group96896}
                  className="mt-12"

                />
              </div>
              <div className="" style={{ gridArea: "1 / 2 / 3 / 4" }}>
                <img src={Group96898} />
              </div>
              <div className="" style={{ gridArea: "3 / 2 / 4 / 3" }}>

                <img
                  src={Group96897}
                  className="mt-12"

                />
              </div>
              <img
                src={Group96901}
                className="mt-12"
                style={{ gridArea: "3 / 3 / 4 / 5" }}
              />
              <img src={Group96900} style={{ gridArea: "1 / 4 / 2 / 5" }} />
              <img src={Group96899} style={{ gridArea: "2 / 4 / 3 / 5" }} />
            </div>
          </div> */}
        </div>





        <Phases />


        {/* ---------- Have any question (Section) ---------- */}
        <div className="container mx-auto sm:px-4">

          <div className="flex flex-col sm:flex-row items-center justify-between max-md:[flex-col]">
            <div className="w-[90%] sm:w-[50%] mb-10">
              <h6
                className=" text-5xl mb-2 text-white font-normal"
                style={{ lineHeight: 1, fontFamily: "Zen Dots" }}
              >
                Have any question?
              </h6>
              <p className="text-white mb-4">
                Curious about 3dotlink? Explore our frequently asked questions to
                find answers
              </p>
              <div className="flex justify-between text-white ">
                <span>General</span>
                <span>Pre ICB</span>
                <span>Token</span>
                <span>Client</span>
                <span>Legal</span>
              </div>
              <hr />

              <div className="flex flex-col justify-around gap-4">
                <div className="bg-[#870C27]">
                  <div className="flex justify-around">
                    <h6 className="text-[#EE153D]">
                      How do I create NFTs on 3dotlink?
                    </h6>
                    <img src={Frame53} alt="" />
                  </div>

                  <div className="bg-[#870C27]">
                    <p className="text-white ">
                      Artists and creators can use our AI-integrated platform to
                      generate NFTs by providing specific inputs, such as the
                      desired features and elements for their digital artwork.
                    </p>
                  </div>
                </div>

                <div className="bg-[#870C27]">
                  <h6 className="text-white">
                    What kind of art does 3dotlink support?
                  </h6>
                </div>

                <div className="bg-[#870C27]">
                  <h6 className="text-white">
                    How are digital artworks verified for authenticity?
                  </h6>
                </div>

                <div className="bg-[#870C27]">
                  <h6 className="text-white">
                    Can artists access and manage their collections on 3dotlink?
                  </h6>
                </div>
              </div>
            </div>

            <div className="w-[60%] sm:w-[45%]">
              <img src={Hero} alt="" className="w-full" />
            </div>
          </div>

        </div>
      </div>
    </>
  );
};

export default FirstPage;
